version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - INTERNAL_PORT=${INTERNAL_PORT}
      - EXTERNAL_PORT=${EXTERNAL_PORT}
      - MIGRATION_VERSION=1.2.0
    volumes:
      - ./start.sh:/docker-entrypoint-initdb.d/start.sh
      - ./migrations:/app/migrations
      - ./users.txt:/app/users.txt
    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
    restart: unless-stopped

  generation:
    image: postgres:latest
    command: sh -c "pip install -r /app/requirements.txt && python /app/datageneration.py"
    volumes:
      - ./requirements.txt:/app/requirements.txt
      - ./generation/:/app/generation
      - ./datageneration.py:/app/datageneration.py
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - PORT=${INTERNAL_PORT}
      - AMOUNT=1000000

  indexing:
    image: python:3.9
    command: sh -c "pip install -r /app/requirements.txt && python /app/runner.py"
    volumes:
      - ./requirements.txt:/app/requirements.txt
      - ./runner.py:/app/runner.py
      - ./optimization/create_indexes.sql:/app/create_indexes.sql
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - PORT=${INTERNAL_PORT}
      - FILE=create_indexes.sql

  partition:
    image: python:3.9
    command: sh -c "pip install -r /app/requirements.txt && python /app/runner.py"
    volumes:
      - ./requirements.txt:/app/requirements.txt
      - ./runner.py:/app/runner.py
      - ./optimization/partition.sql:/app/partition.sql
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - PORT=${INTERNAL_PORT}
      - FILE=partition.sql

  backups:
    image: postgres:latest
    command: sh -c "/app/backup.sh"
    volumes:
      - ./backups:/app/backups
      - ./backup.sh:/app/backup.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - PORT=${INTERNAL_PORT}
      - N=${N}
      - M=${M}
      - BACKUP_DIR=${BACKUP_DIR}

#  backups:
#    image: python:3.9
#    command: sh -c "apt-get update && apt-get upgrade -y && apt-get install -y postgresql-client && echo "QWERTQWERQWERTQWER" && find / -name pg_dump && pg_dump --version && python /app/backup.py"
#    volumes:
#      - ./backups:/app/backups
#      - ./backup.py:/app/backup.py
#    depends_on:
#      - postgres
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_HOST=${POSTGRES_HOST}
#      - PORT=${INTERNAL_PORT}
#      - N=${N}
#      - M=${M}
#      - BACKUP_DIR=${BACKUP_DIR}