global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['pg_exporter:9187']
  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]
  - job_name: 'node'
    static_configs:
      - targets: [ 'node_exporter:9100' ]